<a href="https://colab.research.google.com/github/Kelf1729/Perceptron_Manual/blob/master/Projeto_Inicial_Perceptron_de_uma_camada.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# PROJETO MODELO SIMPLES DE UM PERCEPTRON DE UMA CAMADA 

In [0]:
#Importação de bibliotecas 
import tensorflow as tf  
import numpy as np 

Criando as variáveis de entrada do modelo 

In [3]:
X = np.array([[0.0, 0.0],
              [0.0, 1.0],
              [1.0, 0.0],
              [1.0, 1.0]]) #Criando matriz (X1 e X2)
X #Visualizando resultado 

array([[0., 0.],
       [0., 1.],
       [1., 0.],
       [1., 1.]])

Criando variável de classes 

In [4]:
Y = np.array([[0.0], [0.0], [0.0], [1.0]]) #Classificação correta
Y #visualizando os resultados 

array([[0.],
       [0.],
       [0.],
       [1.]])

Criando a matriz de pesos do modelo 

In [0]:
W = tf.Variable(tf.zeros([2,1], dtype = tf.float64)) #Definindo uma matriz de zeros com o 2 linhas e 1 coluna e tipo de zeros float 

In [0]:
#Para visualizar as variáveis é necessário inicializar o mesmo, logo :
init = tf.global_variables_initializer()

In [0]:
#Para obter a camada de Saída realizamos a multiplicação da matriz de entradas pela matriz de pesos 
camada_saida = tf.matmul(X, W)

Criando a função de ativação para analisar os resultados da camada de saída

In [0]:
# math greater retorna um True or False se o primeiro valor for superior ao primeiro
#Convertendo o resultado da função para um tipo float64
#A função de ativação deve ser aplicada em cada elemento da matriz camada de saída 
def Step(x): #Função Step de sinais zero ou 1 (função degrau)
  return tf.cast(tf.to_float(tf.math.greater_equal(x, 1)), tf.float64) 

Criando uma camada de resultados para a camada de saída 

In [0]:
camada_saida_ativacao = Step(camada_saida) #Aplicando a função Step a cada elemento 

Criando o elemento de verificação dos resultados, ou seja, uma variável de erro 

In [0]:
#Variável de Erro
error = tf.subtract(Y, camada_saida_ativacao) #verificando o resultado esperado Y com a previsão da função de ativação 

In [0]:
#Criar uma variável que recebe a multiplicação da entrada(X) pelos erros
#Contudo a ordem das matrizes não permite a multiplicação sem a transposta da X 
delta = tf.matmul(X, error, transpose_a= True) #Transposta de X é verdade

Criando a variável de treinamento 

In [0]:
#0.01 é a taxa de aprendizado dos valores de delta 
#Mais a soma dos pesos W com o add 
treinamento = tf.assign(W, tf.add(W, tf.multiply(delta, 0.1))) 

In [52]:
with tf.Session() as sess: #Criando 
  sess.run(init) #Inicializando as variáveis 
  print('\n')
  #Criando o loop para modelar as épocas 
  epocas = 0
  for i in range(10**6):
    epocas += 1
    erro_total, _ = sess.run([error, treinamento]) #O traço é apenas para compor a recepção de treinamento que é none
    erro_soma = tf.reduce_sum(erro_total) #soma dos erros do vetor Erro total 
    print('Época: ', epocas, 'Erro Soma: ', sess.run(erro_soma))
    #Critério de parada para o loop de correção 
    if erro_soma.eval() == 0.0:
      break
    #Obtendo os valores dos pesos corrigidos
    W_final = sess.run(W)



Época:  1 Erro Soma:  1.0
Época:  2 Erro Soma:  1.0
Época:  3 Erro Soma:  1.0
Época:  4 Erro Soma:  1.0
Época:  5 Erro Soma:  1.0
Época:  6 Erro Soma:  0.0


In [53]:
W_final

array([[0.5],
       [0.5]])

#Criando um teste para analisar os pesos corretos e ver a qualidade dos resultados 

In [55]:
#teste dos pesos corrigidos 
camada_saida_teste = tf.matmul(X, W_final) #Nova multiplicação de teste
camada_saida_ativacao_teste = Step(camada_saida_teste) #aplicando a função de ativação para obter os valores 
with tf.Session() as sess: #Realizando as operações 
  sess.run(init)
  print(sess.run(camada_saida_ativacao_teste)) #obtendo os valores de previsão 

[[0.]
 [0.]
 [0.]
 [1.]]
